# Generated by Django 5.2.17 on 2026-09-18 18:59

import artists.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180)),
                ('artwork', models.ImageField(blank=True, null=True, upload_to='tracks/artwork/')),
                ('mp3', models.FileField(blank=True, storage=artists.models.protected_storage, upload_to='tracks/')),
                ('wav', models.FileField(blank=True, storage=artists.models.protected_storage, upload_to='tracks/')),
                ('preview_seconds', models.PositiveSmallIntegerField(default=30)),
                ('price_inr', models.PositiveIntegerField(default=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='artists.artistprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('artist', 'slug'), name='unique_artist_track_slug')],
            },
        ),
    ]
